name: Python Weather App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt install -y libegl1
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-devel.txt
        python -m pip install pyinstaller
    - name: Create Executable
      run: |
        pyinstaller -F -w --icon=resources/images/icon.png main.py
    - uses: actions/upload-artifact@v3
      with:
      name: Ubuntu Artifact
      path: dist/main
  